/* Getting the list of top 10 customer based on their total spending also with the address. */

SELECT C.FIRST_NAME,
	C.LAST_NAME,
	C.EMAIL,
	MAX(A.ADDRESS),
	SUM(P.AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMER C
JOIN PAYMENT P ON C.CUSTOMER_ID = P.CUSTOMER_ID
JOIN ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID
GROUP BY C.CUSTOMER_ID,
	C.FIRST_NAME,
	C.LAST_NAME,
	C.EMAIL
ORDER BY TOTAL_SPENDING DESC
LIMIT 10;