/*
Query that includes the replacement cost, the total count of DVDs with that replacement cost, the total revenue generated 
from rentals of those DVDs, and the average revenue per DVD
*/

SELECT REPLACEMENT_COST,
	COUNT(*) AS TOTAL_COUNT,
	SUM(PAYMENT.AMOUNT) AS TOTAL_REVENUE,
	AVG(PAYMENT.AMOUNT) AS AVERAGE_REVENUE
FROM FILM
JOIN INVENTORY ON FILM.FILM_ID = INVENTORY.FILM_ID
JOIN RENTAL ON INVENTORY.INVENTORY_ID = RENTAL.INVENTORY_ID
JOIN PAYMENT ON RENTAL.RENTAL_ID = PAYMENT.RENTAL_ID
GROUP BY REPLACEMENT_COST
ORDER BY REPLACEMENT_COST;