/* 
DVDs that have been frequently replaced due to loss or damage
*/
SELECT F.FILM_ID,
	F.TITLE,
	COUNT(R.RENTAL_ID) AS REPLACEMENT_COUNT
FROM FILM F
JOIN INVENTORY I ON F.FILM_ID = I.FILM_ID
JOIN RENTAL R ON I.INVENTORY_ID = R.INVENTORY_ID
GROUP BY F.FILM_ID,
	F.TITLE
ORDER BY REPLACEMENT_COUNT DESC;