/* Helps identify and rank the most popular category of items in each store and includes categories with counts.*/

WITH CATEGORYCOUNTS AS
	(SELECT S.STORE_ID,
			A.ADDRESS,
			C.NAME AS CATEGORY_NAME,
			COUNT(*) AS CATEGORY_COUNT
		FROM STORE S
		JOIN ADDRESS A ON S.ADDRESS_ID = A.ADDRESS_ID
		JOIN INVENTORY I ON S.STORE_ID = I.STORE_ID
		JOIN FILM F ON I.FILM_ID = F.FILM_ID
		JOIN FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID
		JOIN CATEGORY C ON FC.CATEGORY_ID = C.CATEGORY_ID
		GROUP BY S.STORE_ID,
			A.ADDRESS,
			C.NAME),
	CATEGORYRANKS AS
	(SELECT *,
			ROW_NUMBER() OVER (PARTITION BY CATEGORY_NAME
			ORDER BY CATEGORY_COUNT DESC) AS RANK
		FROM CATEGORYCOUNTS)
SELECT STORE_ID,
	ADDRESS,
	CATEGORY_NAME,
	CATEGORY_COUNT
FROM CATEGORYRANKS
WHERE RANK = 1
	OR CATEGORY_COUNT = 0
ORDER BY CATEGORY_NAME,
	CATEGORY_COUNT DESC;