/* Which address the most rentals are made */

SELECT A.ADDRESS,
	COUNT(R.RENTAL_ID) AS RENTAL_COUNT
FROM RENTAL R
JOIN CUSTOMER C ON R.CUSTOMER_ID = C.CUSTOMER_ID
JOIN ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID
GROUP BY A.ADDRESS
ORDER BY RENTAL_COUNT DESC
Limit 50;
