/* Getting the top 10 city where there is highest count of rental made.*/

SELECT CI.CITY,
	COUNT(R.RENTAL_ID) AS RENTAL_COUNT
FROM CUSTOMER C
JOIN ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID
JOIN CITY CI ON A.CITY_ID = CI.CITY_ID
JOIN RENTAL R ON C.CUSTOMER_ID = R.CUSTOMER_ID
GROUP BY CI.CITY
ORDER BY RENTAL_COUNT DESC
LIMIT 50;