/*
Retrieving the sales for each category at each store
*/
SELECT S.STORE_ID,
    C.NAME AS CATEGORY_NAME,
    SUM(P.AMOUNT) AS CATEGORY_SALES
FROM STORE S
JOIN CUSTOMER CU ON S.STORE_ID = CU.STORE_ID
JOIN PAYMENT P ON CU.CUSTOMER_ID = P.CUSTOMER_ID
JOIN RENTAL R ON CU.CUSTOMER_ID = R.CUSTOMER_ID
JOIN INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
JOIN FILM F ON I.FILM_ID = F.FILM_ID
JOIN FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID
JOIN CATEGORY C ON FC.CATEGORY_ID = C.CATEGORY_ID
GROUP BY S.STORE_ID, C.NAME
ORDER BY S.STORE_ID, CATEGORY_SALES DESC;
